tasks:
    - t1:
        type: "bash"
        response: "str"
        action: 'echo "{search_text}" | netcat -N 10.61.8.75 10000'
        parameters:
            - search_text:
                type: "str"
    - t2:
        type: "bash"
        response: "str"
        action: ""
    - t3:
        type: "bash"
        response: "str"
        action: ""

master:
    ip: 10.61.8.75
    port: 6969

heartbeat-port: 9000

nodes:
  - node1:
      ip: 10.61.119.144
      port: 6969
      tasks:
        - t1
        - t2
#   - node2:
#       ip: 10.81.49.126
#       port: 6969
#       tasks: 
#         - t2
#   - node3:
#       ip: 10.81.49.127
#       port: 6969
#       tasks: 
#         - t3

client:
    tasks:
        - t1:
            protocol: "http"
            method: "POST"
            endpoint: "get-movie-name"
            parameters:
                - search-text:
                    type: str