nodes:
  - node1:
      ip: 10.81.49.125
      port: 6969
      task: t1
  - node2:
      ip: 10.81.49.126
      port: 6969
      task: t2
  - node3:
      ip: 10.81.49.127
      port: 6969
      task: t3