tasks:
    - t1:
        type: "bash"
        response: "str"
        action: "echo {search_text}"
        parameters:
            - search_text:
                type: "str"
    - t2:
        type: "bash"
        response: "str"
        action: ""
    - t3:
        type: "bash"
        response: "str"
        action: ""

master:
    ip: 10.81.49.125
    port: 6969

heartbeat-port: 9000

nodes:
  - node1:
      ip: 10.81.49.125
      port: 6969
      tasks:
        - t1
        - t2
  - node2:
      ip: 10.81.49.126
      port: 6969
      tasks: 
        - t2
  - node3:
      ip: 10.81.49.127
      port: 6969
      tasks: 
        - t3
