# type - "bash", "python", "https"
# response - "str", "image", "blob", "None"
# parameters are optional

tasks:
    - t1:
        type:
        response:
        action: 
        parameters:
            - param1:
                type:
            - param2:
                type:
            - param3:
                type:
    - t2:
        type:
        response:
        action: 
    - t3:
        type: 
        response:
        action: 
        parameters:
            - param1:
                type:

master:
    ip:
    port:

heartbeat-port:

nodes:
  - node1:
      ip:
      port:
      tasks:
  - node2:
      ip:
      port:
      tasks:
  - node3:
      ip:
      port:
      tasks:

client:
    tasks:
        - get-movies-name:
            protocol:
            method:
            endpoint:
            parameters:
                - param1:
                    type: 
                - param2:
                    type: 